### ISSUE TITLE
Another way to enter button changes?

### ISSUE THREAD

**Issue by Kay6579** [ShadowPrince/advremap#10]
Need to use this for my vita, since my start button doesn't work. The app requires me to press the button I want to remap before I can change it but unfortunately the button is completely non-responsive. Would it be possible to implement another way to choose which buttons are to be remapped?

**Comment by shdwp** [comment]
It will be implemented in the next version, and now, if you want, I can manually create you a profile which you can apply to any game. Just write a list of things to remap.

**Comment by Kay6579** [comment]
That would be helpful. I only need to remap the START button. To the bottom right corner of the screen, maybe. Also, would it be possible to add vitashell and molecular shell to the list of compatible apps?

**Comment by shdwp** [comment]
Here's 2 plugins with back touchscreen top left and right (respectively) remapped to the Start: https://www.dropbox.com/s/vndr4ocxj19gk5e/advremap_start_presets.zip?dl=0 

backleftstart.suprx remap top left corner of the back touchscreen to the start, and backrightstart.suprx does the same with top right. You have to place them in `ux0:tai/` and enable using the `config.txt` for the specified games (as every other tai plugin).

Regarding vitaShell/molecularShell - last time I've checked it were not possible to use plugins with homebrew software.

**Comment by Kay6579** [comment]
Thank you very much!!!

**Comment by Kay6579** [comment]
Sorry to trouble you again, but I have two issues not covered in the
troubleshooting section. First, I'm unable to delete any changes I've made
on the adv remap app. I've tried deleting on the software, deleting the
plugin for each game, reinstalling the app and restarting. Each time I
reload, the very first set of remaps I made return. Is there a registry
file I need to delete to reset it to default? The second issue is any
backups I apply adv remap to, I get the c2-12828-1 error on launch,
everytime. I've tried with 4 different backups and I get the same error.

Sorry to mail you directly, if you prefer I could open an issue on Github.
Thanks again.

**Comment by shdwp** [comment]
By "backups" do you mean vitamin/mai? These things aren't supported (and it's not that easy to do that). 

Configuration files itself are in `ux0:data/advremap/`, you can delete them there if you have issues. Configuration saved when you exit game menu (so you are back into games list), maybe here's that. Do you exit the screen after deleting the remaps?

Also, plugins that I've provided (left/rightbackstart) aren't supposed to be configured at all.

**Comment by Kay6579** [comment]
Ok. I guess I'll need to look for a permanent hardware fix. A bit difficult
to find vita technicians and/or parts where I live, but I'll manage. Thanks
for everything.
