### ISSUE TITLE
L -> cɔ NE

### ISSUE THREAD

**Issue by pakrett** [ShadowPrince/advremap#7]
I have tested the plugin on "PCSF00482 - The Ratchet & Clank Trilogy" the plugin loads when I start the game and it works great but I want to remap the "back touchscreen North East" to "L" and I can't...

For exemple when I set up like that : "cɔ NE -> L" it works.
(when I push back touchscreen North East it does "L")

But I want the opposite, like this : "L -> cɔ NE" and it's not possible I can only set up like this "L -> cɔ"
Can you correct this ?

Anyway thanks to you for this great plugin, I hope soon I will finally able to play Ratchet & Clank correctly !

**Comment by ShadowPrince** [comment]
When you test it in the app does it work correctly?

**Comment by pakrett** [comment]
Yes it works, you right.
Maybe I'm not touching the right place for the games to detect it ?
A little more left or right ?
I will try other positions.

**Comment by pakrett** [comment]
Ok it works... It's a mistake, your plugin is already perfect for me ^^ Thanks for all !!!

**Comment by pakrett** [comment]
Another mistake, it's possible to invert 2 buttons with this config : 
cɔ NE -> L
L -> cɔ

But not like this :
L -> cɔ
cɔ NE -> L

**Comment by ShadowPrince** [comment]
Yea, there will be "do nothing" option as well as option to manually add actions.
